repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.12.0
    hooks:
    -   id: black
        exclude: ^hordelib/nodes/.*\..*$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
    -    id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.19.1'
    hooks:
    -   id: mypy
        exclude: ^examples/.*$ # FIXME
        additional_dependencies: [
            pydantic,
            strenum,
            types-colorama,
            types-docutils,
            types-Pillow, types-psutil,
            types-Pygments,
            types-pywin32,
            types-PyYAML,
            types-regex,
            types-requests,
            types-setuptools,
            types-tabulate,
            types-tqdm,
            types-urllib3,
            horde_sdk==0.14.3,
            horde_model_reference==0.9.0,
        ]
